<?xml version="1.0"?>
<!DOCTYPE issues [
<!ELEMENT issues (issue*)>
<!ATTLIST issues burpVersion CDATA "">
<!ATTLIST issues exportTime CDATA "">
<!ELEMENT issue (serialNumber, type, name, host, path, location, severity, confidence, issueBackground?, remediationBackground?, references?, vulnerabilityClassifications?, issueDetail?, issueDetailItems?, remediationDetail?, requestresponse*, collaboratorEvent*, infiltratorEvent*, staticAnalysis*, dynamicAnalysis*, prototypePollution*)>
<!ELEMENT serialNumber (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host ip CDATA "">
<!ELEMENT path (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT confidence (#PCDATA)>
<!ELEMENT issueBackground (#PCDATA)>
<!ELEMENT remediationBackground (#PCDATA)>
<!ELEMENT references (#PCDATA)>
<!ELEMENT vulnerabilityClassifications (#PCDATA)>
<!ELEMENT issueDetail (#PCDATA)>
<!ELEMENT issueDetailItems (issueDetailItem*)>
<!ELEMENT issueDetailItem (#PCDATA)>
<!ELEMENT remediationDetail (#PCDATA)>
<!ELEMENT requestresponse (request?, response?, responseRedirected?)>
<!ELEMENT request (#PCDATA)>
<!ATTLIST request method CDATA "">
<!ATTLIST request base64 (true|false) "false">
<!ELEMENT response (#PCDATA)>
<!ATTLIST response base64 (true|false) "false">
<!ELEMENT responseRedirected (#PCDATA)>
<!ELEMENT sender (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT conversation (#PCDATA)>
<!ELEMENT recipient (#PCDATA)>
<!ELEMENT recipients (recipient*)>
<!ELEMENT smtp (sender, recipients, message, conversation)>
<!ELEMENT collaboratorEvent (interactionType, originIp, time, lookupType?, lookupHost?, requestresponse?, smtp?)>
<!ELEMENT interactionType (#PCDATA)>
<!ELEMENT originIp (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT lookupType (#PCDATA)>
<!ELEMENT lookupHost (#PCDATA)>
<!ELEMENT infiltratorEvent (parameterName, platform, signature, stackTrace?, parameterValue?, collaboratorEvent)>
<!ELEMENT parameterName (#PCDATA)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT signature (#PCDATA)>
<!ELEMENT stackTrace (#PCDATA)>
<!ELEMENT parameterValue (#PCDATA)>
<!ELEMENT dynamicAnalysis (source, sink, sourceStackTrace, sinkStackTrace, eventListenerStackTrace, sourceValue, sinkValue, eventHandlerData, eventHandlerDataType, eventHandlerManipulatedData, poc, origin, isOriginChecked, sourceElementId, sourceElementName, eventFiredEventName, eventFiredElementId, eventFiredElementName, eventFiredOuterHtml)>
<!ELEMENT prototypePollution (poc, pollutionTechnique, pollutionType)>
<!ELEMENT staticAnalysis (source, sink, codeSnippets)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT sink (#PCDATA)>
<!ELEMENT sourceStackTrace (#PCDATA)>
<!ELEMENT sinkStackTrace (#PCDATA)>
<!ELEMENT eventListenerStackTrace (#PCDATA)>
<!ELEMENT sourceValue (#PCDATA)>
<!ELEMENT sinkValue (#PCDATA)>
<!ELEMENT eventHandlerData (#PCDATA)>
<!ELEMENT eventHandlerDataType (#PCDATA)>
<!ELEMENT sourceElementId (#PCDATA)>
<!ELEMENT sourceElementName (#PCDATA)>
<!ELEMENT eventFiredEventName (#PCDATA)>
<!ELEMENT eventFiredElementId (#PCDATA)>
<!ELEMENT eventFiredElementName (#PCDATA)>
<!ELEMENT eventFiredOuterHtml (#PCDATA)>
<!ELEMENT eventHandlerManipulatedData (#PCDATA)>
<!ELEMENT poc (#PCDATA)>
<!ELEMENT origin (#PCDATA)>
<!ELEMENT isOriginChecked (#PCDATA)>
<!ELEMENT codeSnippets (codeSnippet*)>
<!ELEMENT codeSnippet (#PCDATA)>
<!ELEMENT pollutionTechnique (#PCDATA)>
<!ELEMENT pollutionType (#PCDATA)>
]>
<issues burpVersion="2023.8.1" exportTime="Sun Aug 13 23:48:58 GMT 2023">
  <issue>
    <serialNumber>6640892796658935808</serialNumber>
    <type>134217728</type>
    <name><![CDATA[Session token in URL]]></name>
    <host ip="172.20.0.3">http://web</host>
    <path><![CDATA[/wp-admin/admin-ajax.php]]></path>
    <location><![CDATA[/wp-admin/admin-ajax.php]]></location>
    <severity>Medium</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[<p>Sensitive information within URLs may be logged in various locations, including the user's browser, the web server, and any forward or reverse proxy servers between the two endpoints. URLs may also be displayed on-screen, bookmarked or emailed around by users. They may be disclosed to third parties via the Referer header when any off-site links are followed. Placing session tokens into the URL increases the risk that they will be captured by an attacker.</p>]]></issueBackground>
    <remediationBackground><![CDATA[<p>Applications should use an alternative mechanism for transmitting session tokens, such as HTTP cookies or hidden fields in forms that are submitted using the POST method.</p>]]></remediationBackground>
    <issueDetail><![CDATA[The URL in the request appears to contain a session token within the query string:<ul><li>http://web/wp-admin/admin-ajax.php?_panelsnonce=fuzz&amp;action=so_panels_live_editor_preview</li></ul>]]></issueDetail>
    <issueDetailItems>
      <issueDetailItem><![CDATA[http://web/wp-admin/admin-ajax.php?_panelsnonce=fuzz&action=so_panels_live_editor_preview]]></issueDetailItem>
    </issueDetailItems>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC93cC1hZG1pbi9hZG1pbi1hamF4LnBocD9fcGFuZWxzbm9uY2U9ZnV6eiZhY3Rpb249c29fcGFuZWxzX2xpdmVfZWRpdG9yX3ByZXZpZXcgSFRUUC8xLjANCkhvc3Q6IHdlYg0KDQo=]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgNDAwIEJhZCBSZXF1ZXN0DQpEYXRlOiBTdW4sIDEzIEF1ZyAyMDIzIDIzOjQ1OjU3IEdNVA0KU2VydmVyOiBBcGFjaGUvMi40LjU2IChEZWJpYW4pDQpDb250ZW50LUxlbmd0aDogMzAyDQpDb25uZWN0aW9uOiBjbG9zZQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWw7IGNoYXJzZXQ9aXNvLTg4NTktMQ0KDQo8IURPQ1RZUEUgSFRNTCBQVUJMSUMgIi0vL0lFVEYvL0RURCBIVE1MIDIuMC8vRU4iPgo8aHRtbD48aGVhZD4KPHRpdGxlPjQwMCBCYWQgUmVxdWVzdDwvdGl0bGU+CjwvaGVhZD48Ym9keT4KPGgxPkJhZCBSZXF1ZXN0PC9oMT4KPHA+WW91ciBicm93c2VyIHNlbnQgYSByZXF1ZXN0IHRoYXQgdGhpcyBzZXJ2ZXIgY291bGQgbm90IHVuZGVyc3RhbmQuPGJyIC8+CjwvcD4KPGhyPgo8YWRkcmVzcz5BcGFjaGUvMi40LjU2IChEZWJpYW4pIFNlcnZlciBhdCAxNzIuMjAuMC4zIFBvcnQgODA8L2FkZHJlc3M+CjwvYm9keT48L2h0bWw+Cg==]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>1957115514450675712</serialNumber>
    <type>134217728</type>
    <name><![CDATA[Private IP addresses disclosed]]></name>
    <host ip="172.20.0.3">http://web</host>
    <path><![CDATA[/wp-admin/admin-ajax.php]]></path>
    <location><![CDATA[/wp-admin/admin-ajax.php]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[<p>RFC 1918 specifies ranges of IP addresses that are reserved for use in private networks and cannot be routed on the public Internet. Although various methods exist by which an attacker can determine the public IP addresses in use by an organization, the private addresses used internally cannot usually be determined in the same ways.</p>
<p>Discovering the private addresses used within an organization can help an attacker in carrying out network-layer attacks aiming to penetrate the organization's internal infrastructure. </p>]]></issueBackground>
    <remediationBackground><![CDATA[<p>There is not usually any good reason to disclose the internal IP addresses used within an organization's infrastructure. If these are being returned in service banners or debug messages, then the relevant services should be configured to mask the private addresses. If they are being used to track back-end servers for load balancing purposes, then the addresses should be rewritten with innocuous identifiers from which an attacker cannot infer any useful information about the infrastructure.</p>]]></remediationBackground>
    <issueDetail><![CDATA[The following RFC 1918 IP address was disclosed in the response:<ul><li>172.20.0.3</li></ul>]]></issueDetail>
    <issueDetailItems>
      <issueDetailItem><![CDATA[172.20.0.3]]></issueDetailItem>
    </issueDetailItems>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC93cC1hZG1pbi9hZG1pbi1hamF4LnBocD9fcGFuZWxzbm9uY2U9ZnV6eiZhY3Rpb249c29fcGFuZWxzX2xpdmVfZWRpdG9yX3ByZXZpZXcgSFRUUC8xLjANCkhvc3Q6IHdlYg0KDQo=]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgNDAwIEJhZCBSZXF1ZXN0DQpEYXRlOiBTdW4sIDEzIEF1ZyAyMDIzIDIzOjQ1OjU3IEdNVA0KU2VydmVyOiBBcGFjaGUvMi40LjU2IChEZWJpYW4pDQpDb250ZW50LUxlbmd0aDogMzAyDQpDb25uZWN0aW9uOiBjbG9zZQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWw7IGNoYXJzZXQ9aXNvLTg4NTktMQ0KDQo8IURPQ1RZUEUgSFRNTCBQVUJMSUMgIi0vL0lFVEYvL0RURCBIVE1MIDIuMC8vRU4iPgo8aHRtbD48aGVhZD4KPHRpdGxlPjQwMCBCYWQgUmVxdWVzdDwvdGl0bGU+CjwvaGVhZD48Ym9keT4KPGgxPkJhZCBSZXF1ZXN0PC9oMT4KPHA+WW91ciBicm93c2VyIHNlbnQgYSByZXF1ZXN0IHRoYXQgdGhpcyBzZXJ2ZXIgY291bGQgbm90IHVuZGVyc3RhbmQuPGJyIC8+CjwvcD4KPGhyPgo8YWRkcmVzcz5BcGFjaGUvMi40LjU2IChEZWJpYW4pIFNlcnZlciBhdCAxNzIuMjAuMC4zIFBvcnQgODA8L2FkZHJlc3M+CjwvYm9keT48L2h0bWw+Cg==]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>8151819917125421056</serialNumber>
    <type>134217728</type>
    <name><![CDATA[Cross-origin resource sharing]]></name>
    <host ip="172.20.0.3">http://web</host>
    <path><![CDATA[/wp-admin/admin-ajax.php]]></path>
    <location><![CDATA[/wp-admin/admin-ajax.php]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[<p>An HTML5 cross-origin resource sharing (CORS) policy controls whether and how content running on other domains can perform two-way interaction with the domain that publishes the policy. The policy is fine-grained and can apply access controls per-request based on the URL and other features of the request.</p><p>If another domain is allowed by the policy, then that domain can potentially attack users of the application. If a user is logged in to the application, and visits a domain allowed by the policy, then any malicious content running on that domain can potentially retrieve content from the application, and sometimes carry out actions within the security context of the logged in user.</p>
<p>Even if an allowed domain is not overtly malicious in itself, security vulnerabilities within that domain could potentially be leveraged by an attacker to exploit the trust relationship and attack the application that allows access. CORS policies on pages containing sensitive information should be reviewed to determine whether it is appropriate for the application to trust both the intentions and security posture of any domains granted access.</p>]]></issueBackground>
    <remediationBackground><![CDATA[<p>Any inappropriate domains should be removed from the CORS policy.</p>]]></remediationBackground>
    <issueDetail><![CDATA[The application implements an HTML5 cross-origin resource sharing (CORS) policy for this request.<br><br>Since the Vary: Origin header was not present in the response, reverse proxies and intermediate servers may cache it. This may enable an attacker to carry out cache poisoning attacks.]]></issueDetail>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC93cC1hZG1pbi9hZG1pbi1hamF4LnBocD9fcGFuZWxzbm9uY2U9ZnV6eiZhY3Rpb249c29fcGFuZWxzX2xpdmVfZWRpdG9yX3ByZXZpZXcgSFRUUC8xLjANCkhvc3Q6IHdlYg0KT3JpZ2luOiBodHRwOi8vd2ViDQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBTdW4sIDEzIEF1ZyAyMDIzIDIzOjQ4OjMyIEdNVA0KU2VydmVyOiBBcGFjaGUvMi40LjU2IChEZWJpYW4pDQpYLVBvd2VyZWQtQnk6IFBIUC84LjEuMTgNCkFjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbjogaHR0cDovL3dlYg0KQWNjZXNzLUNvbnRyb2wtQWxsb3ctQ3JlZGVudGlhbHM6IHRydWUNClgtUm9ib3RzLVRhZzogbm9pbmRleA0KWC1Db250ZW50LVR5cGUtT3B0aW9uczogbm9zbmlmZg0KRXhwaXJlczogV2VkLCAxMSBKYW4gMTk4NCAwNTowMDowMCBHTVQNCkNhY2hlLUNvbnRyb2w6IG5vLWNhY2hlLCBtdXN0LXJldmFsaWRhdGUsIG1heC1hZ2U9MA0KUmVmZXJyZXItUG9saWN5OiBzdHJpY3Qtb3JpZ2luLXdoZW4tY3Jvc3Mtb3JpZ2luDQpYLUZyYW1lLU9wdGlvbnM6IFNBTUVPUklHSU4NClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KQ29ubmVjdGlvbjogY2xvc2UNCkNvbnRlbnQtVHlwZTogdGV4dC9odG1sOyBjaGFyc2V0PVVURi04DQoNCgo8IURPQ1RZUEUgaHRtbD4KPGh0bWwgbGFuZz0iZW4tVVMiPgo8aGVhZD4KCTxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KCTxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSI+Cgk8bGluayByZWw9InByb2ZpbGUiIGhyZWY9Imh0dHA6Ly9nbXBnLm9yZy94Zm4vMTEiPgoJPGxpbmsgcmVsPSJwaW5nYmFjayIgaHJlZj0iaHR0cDovL3dlYi94bWxycGMucGhwIj4KCTxtZXRhIG5hbWU9J3JvYm90cycgY29udGVudD0nbWF4LWltYWdlLXByZXZpZXc6bGFyZ2UnIC8+CjxsaW5rIHJlbD0iYWx0ZXJuYXRlIiB0eXBlPSJhcHBsaWNhdGlvbi9yc3MreG1sIiB0aXRsZT0iRnV6emVyIHRhcmdldCAmcmFxdW87IEZlZWQiIGhyZWY9Imh0dHA6Ly93ZWIvP2ZlZWQ9cnNzMiIgLz4KPGxpbmsgcmVsPSJhbHRlcm5hdGUiIHR5cGU9ImFwcGxpY2F0aW9uL3Jzcyt4bWwiIHRpdGxlPSJGdXp6ZXIgdGFyZ2V0ICZyYXF1bzsgQ29tbWVudHMgRmVlZCIgaHJlZj0iaHR0cDovL3dlYi8/ZmVlZD1jb21tZW50cy1yc3MyIiAvPgo8c2NyaXB0Pgp3aW5kb3cuX3dwZW1vamlTZXR0aW5ncyA9IHsiYmFzZVVybCI6Imh0dHBzOlwvXC9zLncub3JnXC9pbWFnZXNcL2NvcmVcL2Vtb2ppXC8xNC4wLjBcLzcyeDcyXC8iLCJleHQiOiIucG5nIiwic3ZnVXJsIjoiaHR0cHM6XC9cL3Mudy5vcmdcL2ltYWdlc1wvY29yZVwvZW1vamlcLzE0LjAuMFwvc3ZnXC8iLCJzdmdFeHQiOiIuc3ZnIiwic291cmNlIjp7ImNvbmNhdGVtb2ppIjoiaHR0cDpcL1wvd2ViXC93cC1pbmNsdWRlc1wvanNcL3dwLWVtb2ppLXJlbGVhc2UubWluLmpzP3Zlcj02LjEuMSJ9fTsKLyohIFRoaXMgZmlsZSBpcyBhdXRvLWdlbmVyYXRlZCAqLwohZnVuY3Rpb24oZSxhLHQpe3ZhciBuLHIsbyxpPWEuY3JlYXRlRWxlbWVudCgiY2FudmFzIikscD1pLmdldENvbnRleHQmJmkuZ2V0Q29udGV4dCgiMmQiKTtmdW5jdGlvbiBzKGUsdCl7dmFyIGE9U3RyaW5nLmZyb21DaGFyQ29kZSxlPShwLmNsZWFyUmVjdCgwLDAsaS53aWR0aCxpLmhlaWdodCkscC5maWxsVGV4dChhLmFwcGx5KHRoaXMsZSksMCwwKSxpLnRvRGF0YVVSTCgpKTtyZXR1cm4gcC5jbGVhclJlY3QoMCwwLGkud2lkdGgsaS5oZWlnaHQpLHAuZmlsbFRleHQoYS5hcHBseSh0aGlzLHQpLDAsMCksZT09PWkudG9EYXRhVVJMKCl9ZnVuY3Rpb24gYyhlKXt2YXIgdD1hLmNyZWF0ZUVsZW1lbnQoInNjcmlwdCIpO3Quc3JjPWUsdC5kZWZlcj10LnR5cGU9InRleHQvamF2YXNjcmlwdCIsYS5nZXRFbGVtZW50c0J5VGFnTmFtZSgiaGVhZCIpWzBdLmFwcGVuZENoaWxkKHQpfWZvcihvPUFycmF5KCJmbGFnIiwiZW1vamkiKSx0LnN1cHBvcnRzPXtldmVyeXRoaW5nOiEwLGV2ZXJ5dGhpbmdFeGNlcHRGbGFnOiEwfSxyPTA7cjxvLmxlbmd0aDtyKyspdC5zdXBwb3J0c1tvW3JdXT1mdW5jdGlvbihlKXtpZihwJiZwLmZpbGxUZXh0KXN3aXRjaChwLnRleHRCYXNlbGluZT0idG9wIixwLmZvbnQ9IjYwMCAzMnB4IEFyaWFsIixlKXtjYXNlImZsYWciOnJldHVybiBzKFsxMjc5ODcsNjUwMzksODIwNSw5ODk1LDY1MDM5XSxbMTI3OTg3LDY1MDM5LDgyMDMsOTg5NSw2NTAzOV0pPyExOiFzKFs1NTM1Niw1NjgyNiw1NTM1Niw1NjgxOV0sWzU1MzU2LDU2ODI2LDgyMDMsNTUzNTYsNTY4MTldKSYmIXMoWzU1MzU2LDU3MzMyLDU2MTI4LDU2NDIzLDU2MTI4LDU2NDE4LDU2MTI4LDU2NDIxLDU2MTI4LDU2NDMwLDU2MTI4LDU2NDIzLDU2MTI4LDU2NDQ3XSxbNTUzNTYsNTczMzIsODIwMyw1NjEyOCw1NjQyMyw4MjAzLDU2MTI4LDU2NDE4LDgyMDMsNTYxMjgsNTY0MjEsODIwMyw1NjEyOCw1NjQzMCw4MjAzLDU2MTI4LDU2NDIzLDgyMDMsNTYxMjgsNTY0NDddKTtjYXNlImVtb2ppIjpyZXR1cm4hcyhbMTI5Nzc3LDEyNzk5NSw4MjA1LDEyOTc3OCwxMjc5OTldLFsxMjk3NzcsMTI3OTk1LDgyMDMsMTI5Nzc4LDEyNzk5OV0pfXJldHVybiExfShvW3JdKSx0LnN1cHBvcnRzLmV2ZXJ5dGhpbmc9dC5zdXBwb3J0cy5ldmVyeXRoaW5nJiZ0LnN1cHBvcnRzW29bcl1dLCJmbGFnIiE9PW9bcl0mJih0LnN1cHBvcnRzLmV2ZXJ5dGhpbmdFeGNlcHRGbGFnPXQuc3VwcG9ydHMuZXZlcnl0aGluZ0V4Y2VwdEZsYWcmJnQuc3VwcG9ydHNbb1tyXV0pO3Quc3VwcG9ydHMuZXZlcnl0aGluZ0V4Y2VwdEZsYWc9dC5zdXBwb3J0cy5ldmVyeXRoaW5nRXhjZXB0RmxhZyYmIXQuc3VwcG9ydHMuZmxhZyx0LkRPTVJlYWR5PSExLHQucmVhZHlDYWxsYmFjaz1mdW5jdGlvbigpe3QuRE9NUmVhZHk9ITB9LHQuc3VwcG9ydHMuZXZlcnl0aGluZ3x8KG49ZnVuY3Rpb24oKXt0LnJlYWR5Q2FsbGJhY2soKX0sYS5hZGRFdmVudExpc3RlbmVyPyhhLmFkZEV2ZW50TGlzdGVuZXIoIkRPTUNvbnRlbnRMb2FkZWQiLG4sITEpLGUuYWRkRXZlbnRMaXN0ZW5lcigibG9hZCIsbiwhMSkpOihlLmF0dGFjaEV2ZW50KCJvbmxvYWQiLG4pLGEuYXR0YWNoRXZlbnQoIm9ucmVhZHlzdGF0ZWNoYW5nZSIsZnVuY3Rpb24oKXsiY29tcGxldGUiPT09YS5yZWFkeVN0YXRlJiZ0LnJlYWR5Q2FsbGJhY2soKX0pKSwoZT10LnNvdXJjZXx8e30pLmNvbmNhdGVtb2ppP2MoZS5jb25jYXRlbW9qaSk6ZS53cGVtb2ppJiZlLnR3ZW1vamkmJihjKGUudHdlbW9qaSksYyhlLndwZW1vamkpKSl9KHdpbmRvdyxkb2N1bWVudCx3aW5kb3cuX3dwZW1vamlTZXR0aW5ncyk7Cjwvc2NyaXB0Pgo8c3R5bGU+CmltZy53cC1zbWlsZXksCmltZy5lbW9qaSB7CglkaXNwbGF5OiBpbmxpbmUgIWltcG9ydGFudDsKCWJvcmRlcjogbm9uZSAhaW1wb3J0YW50OwoJYm94LXNoYWRvdzogbm9uZSAhaW1wb3J0YW50OwoJaGVpZ2h0OiAxZW0gIWltcG9ydGFudDsKCXdpZHRoOiAxZW0gIWltcG9ydGFudDsKCW1hcmdpbjogMCAwLjA3ZW0gIWltcG9ydGFudDsKCXZlcnRpY2FsLWFsaWduOiAtMC4xZW0gIWltcG9ydGFudDsKCWJhY2tncm91bmQ6IG5vbmUgIWltcG9ydGFudDsKCXBhZGRpbmc6IDAgIWltcG9ydGFudDsKfQo8L3N0eWxlPgoJPGxpbmsgcmVsPSdzdHlsZXNoZWV0JyBpZD0nc2l0ZW9yaWdpbi1wcmV2aWV3LXN0eWxlLWNzcycgaHJlZj0naHR0cDovL3dlYi93cC1jb250ZW50L3BsdWdpbnMvc2l0ZW9yaWdpbi1wYW5lbHMvY3NzL2xpdmUtZWRpdG9yLXByZXZpZXcubWluLmNzcz92ZXI9Mi4yMi4xJyBtZWRpYT0nYWxsJyAvPgo8c3R5bGUgaWQ9J2dsb2JhbC1zdHlsZXMtaW5saW5lLWNzcyc+CmJvZHl7LS13cC0tcHJlc2V0LS1jb2xvci0tYmxhY2s6ICMwMDAwMDA7LS13cC0tcHJlc2V0LS1jb2xvci0tY3lhbi1ibHVpc2gtZ3JheTogI2FiYjhjMzstLXdwLS1wcmVzZXQtLWNvbG9yLS13aGl0ZTogI2ZmZmZmZjstLXdwLS1wcmVzZXQtLWNvbG9yLS1wYWxlLXBpbms6ICNmNzhkYTc7LS13cC0tcHJlc2V0LS1jb2xvci0tdml2aWQtcmVkOiAjY2YyZTJlOy0td3AtLXByZXNldC0tY29sb3ItLWx1bWlub3VzLXZpdmlkLW9yYW5nZTogI2ZmNjkwMDstLXdwLS1wcmVzZXQtLWNvbG9yLS1sdW1pbm91cy12aXZpZC1hbWJlcjogI2ZjYjkwMDstLXdwLS1wcmVzZXQtLWNvbG9yLS1saWdodC1ncmVlbi1jeWFuOiAjN2JkY2I1Oy0td3AtLXByZXNldC0tY29sb3ItLXZpdmlkLWdyZWVuLWN5YW46ICMwMGQwODQ7LS13cC0tcHJlc2V0LS1jb2xvci0tcGFsZS1jeWFuLWJsdWU6ICM4ZWQxZmM7LS13cC0tcHJlc2V0LS1jb2xvci0tdml2aWQtY3lhbi1ibHVlOiAjMDY5M2UzOy0td3AtLXByZXNldC0tY29sb3ItLXZpdmlkLXB1cnBsZTogIzliNTFlMDstLXdwLS1wcmVzZXQtLWNvbG9yLS1iYXNlOiAjZmZmZmZmOy0td3AtLXByZXNldC0tY29sb3ItLWNvbnRyYXN0OiAjMDAwMDAwOy0td3AtLXByZXNldC0tY29sb3ItLXByaW1hcnk6ICM5REZGMjA7LS13cC0tcHJlc2V0LS1jb2xvci0tc2Vjb25kYXJ5OiAjMzQ1QzAwOy0td3AtLXByZXNldC0tY29sb3ItLXRlcnRpYXJ5OiAjRjZGNkY2Oy0td3AtLXByZXNldC0tZ3JhZGllbnQtLXZpdmlkLWN5YW4tYmx1ZS10by12aXZpZC1wdXJwbGU6IGxpbmVhci1ncmFkaWVudCgxMzVkZWcscmdiYSg2LDE0NywyMjcsMSkgMCUscmdiKDE1NSw4MSwyMjQpIDEwMCUpOy0td3AtLXByZXNldC0tZ3JhZGllbnQtLWxpZ2h0LWdyZWVuLWN5YW4tdG8tdml2aWQtZ3JlZW4tY3lhbjogbGluZWFyLWdyYWRpZW50KDEzNWRlZyxyZ2IoMTIyLDIyMCwxODApIDAlLHJnYigwLDIwOCwxMzApIDEwMCUpOy0td3AtLXByZXNldC0tZ3JhZGllbnQtLWx1bWlub3VzLXZpdmlkLWFtYmVyLXRvLWx1bWlub3VzLXZpdmlkLW9yYW5nZTogbGluZWFyLWdyYWRpZW50KDEzNWRlZyxyZ2JhKDI1MiwxODUsMCwxKSAwJSxyZ2JhKDI1NSwxMDUsMCwxKSAxMDAlKTstLXdwLS1wcmVzZXQtLWdyYWRpZW50LS1sdW1pbm91cy12aXZpZC1vcmFuZ2UtdG8tdml2aWQtcmVkOiBsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLHJnYmEoMjU1LDEwNSwwLDEpIDAlLHJnYigyMDcsNDYsNDYpIDEwMCUpOy0td3AtLXByZXNldC0tZ3JhZGllbnQtLXZlcnktbGlnaHQtZ3JheS10by1jeWFuLWJsdWlzaC1ncmF5OiBsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLHJnYigyMzgsMjM4LDIzOCkgMCUscmdiKDE2OSwxODQsMTk1KSAxMDAlKTstLXdwLS1wcmVzZXQtLWdyYWRpZW50LS1jb29sLXRvLXdhcm0tc3BlY3RydW06IGxpbmVhci1ncmFkaWVudCgxMzVkZWcscmdiKDc0LDIzNCwyMjApIDAlLHJnYigxNTEsMTIwLDIwOSkgMjAlLHJnYigyMDcsNDIsMTg2KSA0MCUscmdiKDIzOCw0NCwxMzApIDYwJSxyZ2IoMjUxLDEwNSw5OCkgODAlLHJnYigyNTQsMjQ4LDc2KSAxMDAlKTstLXdwLS1wcmVzZXQtLWdyYWRpZW50LS1ibHVzaC1saWdodC1wdXJwbGU6IGxpbmVhci1ncmFkaWVudCgxMzVkZWcscmdiKDI1NSwyMDYsMjM2KSAwJSxyZ2IoMTUyLDE1MCwyNDApIDEwMCUpOy0td3AtLXByZXNldC0tZ3JhZGllbnQtLWJsdXNoLWJvcmRlYXV4OiBsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLHJnYigyNTQsMjA1LDE2NSkgMCUscmdiKDI1NCw0NSw0NSkgNTAlLHJnYigxMDcsMCw2MikgMTAwJSk7LS13cC0tcHJlc2V0LS1ncmFkaWVudC0tbHVtaW5vdXMtZHVzazogbGluZWFyLWdyYWRpZW50KDEzNWRlZyxyZ2IoMjU1LDIwMywxMTIpIDAlLHJnYigxOTksODEsMTkyKSA1MCUscmdiKDY1LDg4LDIwOCkgMTAwJSk7LS13cC0tcHJlc2V0LS1ncmFkaWVudC0tcGFsZS1vY2VhbjogbGluZWFyLWdyYWRpZW50KDEzNWRlZyxyZ2IoMjU1LDI0NSwyMDMpIDAlLHJnYigxODIsMjI3LDIxMikgNTAlLHJnYig1MSwxNjcsMTgxKSAxMDAlKTstLXdwLS1wcmVzZXQtLWdyYWRpZW50LS1lbGVjdHJpYy1ncmFzczogbGluZWFyLWdyYWRpZW50KDEzNWRlZyxyZ2IoMjAyLDI0OCwxMjgpIDAlLHJnYigxMTMsMjA2LDEyNikgMTAwJSk7LS13cC0tcHJlc2V0LS1ncmFkaWVudC0tbWlkbmlnaHQ6IGxpbmVhci1ncmFkaWVudCgxMzVkZWcscmdiKDIsMywxMjkpIDAlLHJnYig0MCwxMTYsMjUyKSAxMDAlKTstLXdwLS1wcmVzZXQtLWR1b3RvbmUtLWRhcmstZ3JheXNjYWxlOiB1cmwoJyN3cC1kdW90b25lLWRhcmstZ3JheXNjYWxlJyk7LS13cC0tcHJlc2V0LS1kdW90b25lLS1ncmF5c2NhbGU6IHVybCgnI3dwLWR1b3RvbmUtZ3JheXNjYWxlJyk7LS13cC0tcHJlc2V0LS1kdW90b25lLS1wdXJwbGUteWVsbG93OiB1cmwoJyN3cC1kdW90b25lLXB1cnBsZS15ZWxsb3cnKTstLXdwLS1wcmVzZXQtLWR1b3RvbmUtLWJsdWUtcmVkOiB1cmwoJyN3cC1kdW90b25lLWJsdWUtcmVkJyk7LS13cC0tcHJlc2V0LS1kdW90b25lLS1taWRuaWdodDogdXJsKCcjd3AtZHVvdG9uZS1taWRuaWdodCcpOy0td3AtLXByZXNldC0tZHVvdG9uZS0tbWFnZW50YS15ZWxsb3c6IHVybCgnI3dwLWR1b3RvbmUtbWFnZW50YS15ZWxsb3cnKTstLXdwLS1wcmVzZXQtLWR1b3RvbmUtLXB1cnBsZS1ncmVlbjogdXJsKCcjd3AtZHVvdG9uZS1wdXJwbGUtZ3JlZW4nKTstLXdwLS1wcmVzZXQtLWR1b3RvbmUtLWJsdWUtb3JhbmdlOiB1cmwoJyN3cC1kdW90b25lLWJsdWUtb3JhbmdlJyk7LS13cC0tcHJlc2V0LS1mb250LXNpemUtLXNtYWxsOiBjbGFtcCgwLjg3NXJlbSwgMC44NzVyZW0gKyAoKDF2dyAtIDAuNDhyZW0pICogMC4yNCksIDFyZW0pOy0td3AtLXByZXNldC0tZm9udC1zaXplLS1tZWRpdW06IGNsYW1wKDFyZW0sIDFyZW0gKyAoKDF2dyAtIDAuNDhyZW0pICogMC4yNCksIDEuMTI1cmVtKTstLXdwLS1wcmVzZXQtLWZvbnQtc2l6ZS0tbGFyZ2U6IGNsYW1wKDEuNzVyZW0sIDEuNzVyZW0gKyAoKDF2dyAtIDAuNDhyZW0pICogMC4yNCksIDEuODc1cmVtKTstLXdwLS1wcmVzZXQtLWZvbnQtc2l6ZS0teC1sYXJnZTogMi4yNXJlbTstLXdwLS1wcmVzZXQtLWZvbnQtc2l6ZS0teHgtbGFyZ2U6IGNsYW1wKDRyZW0sIDRyZW0gKyAoKDF2dyAtIDAuNDhyZW0pICogMTEuNTM4KSwgMTByZW0pOy0td3AtLXByZXNldC0tZm9udC1mYW1pbHktLWRtLXNhbnM6ICJETSBTYW5zIiwgc2Fucy1zZXJpZjstLXdwLS1wcmVzZXQtLWZvbnQtZmFtaWx5LS1pYm0tcGxleC1tb25vOiAnSUJNIFBsZXggTW9ubycsIG1vbm9zcGFjZTstLXdwLS1wcmVzZXQtLWZvbnQtZmFtaWx5LS1pbnRlcjogIkludGVyIiwgc2Fucy1zZXJpZjstLXdwLS1wcmVzZXQtLWZvbnQtZmFtaWx5LS1zeXN0ZW0tZm9udDogLWFwcGxlLXN5c3RlbSxCbGlua01hY1N5c3RlbUZvbnQsIlNlZ29lIFVJIixSb2JvdG8sT3h5Z2VuLVNhbnMsVWJ1bnR1LENhbnRhcmVsbCwiSGVsdmV0aWNhIE5ldWUiLHNhbnMtc2VyaWY7LS13cC0tcHJlc2V0LS1mb250LWZhbWlseS0tc291cmNlLXNlcmlmLXBybzogIlNvdXJjZSBTZXJpZiBQcm8iLCBzZXJpZjstLXdwLS1wcmVzZXQtLXNwYWNpbmctLTMwOiBjbGFtcCgxLjVyZW0sIDV2dywgMnJlbSk7LS13cC0tcHJlc2V0LS1zcGFjaW5nLS00MDogY2xhbXAoMS44cmVtLCAxLjhyZW0gKyAoKDF2dyAtIDAuNDhyZW0pICogMi44ODUpLCAzcmVtKTstLXdwLS1wcmVzZXQtLXNwYWNpbmctLTUwOiBjbGFtcCgyLjVyZW0sIDh2dywgNC41cmVtKTstLXdwLS1wcmVzZXQtLXNwYWNpbmctLTYwOiBjbGFtcCgzLjc1cmVtLCAxMHZ3LCA3cmVtKTstLXdwLS1wcmVzZXQtLXNwYWNpbmctLTcwOiBjbGFtcCg1cmVtLCA1LjI1cmVtICsgKCgxdncgLSAwLjQ4cmVtKSAqIDkuMDk2KSwgOHJlbSk7LS13cC0tcHJlc2V0LS1zcGFjaW5nLS04MDogY2xhbXAoN3JlbSwgMTR2dywgMTFyZW0pO31ib2R5IHsgbWFyZ2luOiAwOy0td3AtLXN0eWxlLS1nbG9iYWwtLWNvbnRlbnQtc2l6ZTogNjUwcHg7LS13cC0tc3R5bGUtLWdsb2JhbC0td2lkZS1zaXplOiAxMjAwcHg7IH0ud3Atc2l0ZS1ibG9ja3MgeyBwYWRkaW5nLXRvcDogdmFyKC0td3AtLXN0eWxlLS1yb290LS1wYWRkaW5nLXRvcCk7IHBhZGRpbmctYm90dG9tOiB2YXIoLS13cC0tc3R5bGUtLXJvb3QtLXBhZGRpbmctYm90dG9tKTsgfS5oYXMtZ2xvYmFsLXBhZGRpbmcgeyBwYWRkaW5nLXJpZ2h0OiB2YXIoLS13cC0tc3R5bGUtLXJvb3QtLXBhZGRpbmctcmlnaHQpOyBwYWRkaW5nLWxlZnQ6IHZhcigtLXdwLS1zdHlsZS0tcm9vdC0tcGFkZGluZy1sZWZ0KTsgfS5oYXMtZ2xvYmFsLXBhZGRpbmcgOndoZXJlKC5oYXMtZ2xvYmFsLXBhZGRpbmcpIHsgcGFkZGluZy1yaWdodDogMDsgcGFkZGluZy1sZWZ0OiAwOyB9Lmhhcy1nbG9iYWwtcGFkZGluZyA+IC5hbGlnbmZ1bGwgeyBtYXJnaW4tcmlnaHQ6IGNhbGModmFyKC0td3AtLXN0eWxlLS1yb290LS1wYWRkaW5nLXJpZ2h0KSAqIC0xKTsgbWFyZ2luLWxlZnQ6IGNhbGModmFyKC0td3AtLXN0eWxlLS1yb290LS1wYWRkaW5nLWxlZnQpICogLTEpOyB9Lmhhcy1nbG9iYWwtcGFkZGluZyA6d2hlcmUoLmhhcy1nbG9iYWwtcGFkZGluZykgPiAuYWxpZ25mdWxsIHsgbWFyZ2luLXJpZ2h0OiAwOyBtYXJnaW4tbGVmdDogMDsgfS5oYXMtZ2xvYmFsLXBhZGRpbmcgPiAuYWxpZ25mdWxsOndoZXJlKDpub3QoLmhhcy1nbG9iYWwtcGFkZGluZykpID4gOndoZXJlKFtjbGFzcyo9IndwLWJsb2NrLSJdOm5vdCguYWxpZ25mdWxsKTpub3QoW2NsYXNzKj0iX18iXSkscCxoMSxoMixoMyxoNCxoNSxoNix1bCxvbCkgeyBwYWRkaW5nLXJpZ2h0OiB2YXIoLS13cC0tc3R5bGUtLXJvb3QtLXBhZGRpbmctcmlnaHQpOyBwYWRkaW5nLWxlZnQ6IHZhcigtLXdwLS1zdHlsZS0tcm9vdC0tcGFkZGluZy1sZWZ0KTsgfS5oYXMtZ2xvYmFsLXBhZGRpbmcgOndoZXJlKC5oYXMtZ2xvYmFsLXBhZGRpbmcpID4gLmFsaWduZnVsbDp3aGVyZSg6bm90KC5oYXMtZ2xvYmFsLXBhZGRpbmcpKSA+IDp3aGVyZShbY2xhc3MqPSJ3cC1ibG9jay0iXTpub3QoLmFsaWduZnVsbCk6bm90KFtjbGFzcyo9Il9fIl0pLHAsaDEsaDIsaDMsaDQsaDUsaDYsdWwsb2wpIHsgcGFkZGluZy1yaWdodDogMDsgcGFkZGluZy1sZWZ0OiAwOyB9LndwLXNpdGUtYmxvY2tzID4gLmFsaWdubGVmdCB7IGZsb2F0OiBsZWZ0OyBtYXJnaW4tcmlnaHQ6IDJlbTsgfS53cC1zaXRlLWJsb2NrcyA+IC5hbGlnbnJpZ2h0IHsgZmxvYXQ6IHJpZ2h0OyBtYXJnaW4tbGVmdDogMmVtOyB9LndwLXNpdGUtYmxvY2tzID4gLmFsaWduY2VudGVyIHsganVzdGlmeS1jb250ZW50OiBjZW50ZXI7IG1hcmdpbi1sZWZ0OiBhdXRvOyBtYXJnaW4tcmlnaHQ6IGF1dG87IH0ud3Atc2l0ZS1ibG9ja3MgPiAqIHsgbWFyZ2luLWJsb2NrLXN0YXJ0OiAwOyBtYXJnaW4tYmxvY2stZW5kOiAwOyB9LndwLXNpdGUtYmxvY2tzID4gKiArICogeyBtYXJnaW4tYmxvY2stc3RhcnQ6IDEuNXJlbTsgfWJvZHkgeyAtLXdwLS1zdHlsZS0tYmxvY2stZ2FwOiAxLjVyZW07IH1ib2R5IC5pcy1sYXlvdXQtZmxvdyA+ICp7bWFyZ2luLWJsb2NrLXN0YXJ0OiAwO21hcmdpbi1ibG9jay1lbmQ6IDA7fWJvZHkgLmlzLWxheW91dC1mbG93ID4gKiArICp7bWFyZ2luLWJsb2NrLXN0YXJ0OiAxLjVyZW07bWFyZ2luLWJsb2NrLWVuZDogMDt9Ym9keSAuaXMtbGF5b3V0LWNvbnN0cmFpbmVkID4gKnttYXJnaW4tYmxvY2stc3RhcnQ6IDA7bWFyZ2luLWJsb2NrLWVuZDogMDt9Ym9keSAuaXMtbGF5b3V0LWNvbnN0cmFpbmVkID4gKiArICp7bWFyZ2luLWJsb2NrLXN0YXJ0OiAxLjVyZW07bWFyZ2luLWJsb2NrLWVuZDogMDt9Ym9keSAuaXMtbGF5b3V0LWZsZXh7Z2FwOiAxLjVyZW07fWJvZHkgLmlzLWxheW91dC1mbG93ID4gLmFsaWdubGVmdHtmbG9hdDogbGVmdDttYXJnaW4taW5saW5lLXN0YXJ0OiAwO21hcmdpbi1pbmxpbmUtZW5kOiAyZW07fWJvZHkgLmlzLWxheW91dC1mbG93ID4gLmFsaWducmlnaHR7ZmxvYXQ6IHJpZ2h0O21hcmdpbi1pbmxpbmUtc3RhcnQ6IDJlbTttYXJnaW4taW5saW5lLWVuZDogMDt9Ym9keSAuaXMtbGF5b3V0LWZsb3cgPiAuYWxpZ25jZW50ZXJ7bWFyZ2luLWxlZnQ6IGF1dG8gIWltcG9ydGFudDttYXJnaW4tcmlnaHQ6IGF1dG8gIWltcG9ydGFudDt9Ym9keSAuaXMtbGF5b3V0LWNvbnN0cmFpbmVkID4gLmFsaWdubGVmdHtmbG9hdDogbGVmdDttYXJnaW4taW5saW5lLXN0YXJ0OiAwO21hcmdpbi1pbmxpbmUtZW5kOiAyZW07fWJvZHkgLmlzLWxheW91dC1jb25zdHJhaW5lZCA+IC5hbGlnbnJpZ2h0e2Zsb2F0OiByaWdodDttYXJnaW4taW5saW5lLXN0YXJ0OiAyZW07bWFyZ2luLWlubGluZS1lbmQ6IDA7fWJvZHkgLmlzLWxheW91dC1jb25zdHJhaW5lZCA+IC5hbGlnbmNlbnRlcnttYXJnaW4tbGVmdDogYXV0byAhaW1wb3J0YW50O21hcmdpbi1yaWdodDogYXV0byAhaW1wb3J0YW50O31ib2R5IC5pcy1sYXlvdXQtY29uc3RyYWluZWQgPiA6d2hlcmUoOm5vdCguYWxpZ25sZWZ0KTpub3QoLmFsaWducmlnaHQpOm5vdCguYWxpZ25mdWxsKSl7bWF4LXdpZHRoOiB2YXIoLS13cC0tc3R5bGUtLWdsb2JhbC0tY29udGVudC1zaXplKTttYXJnaW4tbGVmdDogYXV0byAhaW1wb3J0YW50O21hcmdpbi1yaWdodDogYXV0byAhaW1wb3J0YW50O31ib2R5IC5pcy1sYXlvdXQtY29uc3RyYWluZWQgPiAuYWxpZ253aWRle21heC13aWR0aDogdmFyKC0td3AtLXN0eWxlLS1nbG9iYWwtLXdpZGUtc2l6ZSk7fWJvZHkgLmlzLWxheW91dC1mbGV4e2Rpc3BsYXk6IGZsZXg7fWJvZHkgLmlzLWxheW91dC1mbGV4e2ZsZXgtd3JhcDogd3JhcDthbGlnbi1pdGVtczogY2VudGVyO31ib2R5IC5pcy1sYXlvdXQtZmxleCA+ICp7bWFyZ2luOiAwO31ib2R5e2JhY2tncm91bmQtY29sb3I6IHZhcigtLXdwLS1wcmVzZXQtLWNvbG9yLS1iYXNlKTtjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWNvbnRyYXN0KTtmb250LWZhbWlseTogdmFyKC0td3AtLXByZXNldC0tZm9udC1mYW1pbHktLXN5c3RlbS1mb250KTtmb250LXNpemU6IHZhcigtLXdwLS1wcmVzZXQtLWZvbnQtc2l6ZS0tbWVkaXVtKTtsaW5lLWhlaWdodDogMS42Oy0td3AtLXN0eWxlLS1yb290LS1wYWRkaW5nLXRvcDogdmFyKC0td3AtLXByZXNldC0tc3BhY2luZy0tNDApOy0td3AtLXN0eWxlLS1yb290LS1wYWRkaW5nLXJpZ2h0OiB2YXIoLS13cC0tcHJlc2V0LS1zcGFjaW5nLS0zMCk7LS13cC0tc3R5bGUtLXJvb3QtLXBhZGRpbmctYm90dG9tOiB2YXIoLS13cC0tcHJlc2V0LS1zcGFjaW5nLS00MCk7LS13cC0tc3R5bGUtLXJvb3QtLXBhZGRpbmctbGVmdDogdmFyKC0td3AtLXByZXNldC0tc3BhY2luZy0tMzApO31hOndoZXJlKDpub3QoLndwLWVsZW1lbnQtYnV0dG9uKSl7Y29sb3I6IHZhcigtLXdwLS1wcmVzZXQtLWNvbG9yLS1jb250cmFzdCk7dGV4dC1kZWNvcmF0aW9uOiB1bmRlcmxpbmU7fWE6d2hlcmUoOm5vdCgud3AtZWxlbWVudC1idXR0b24pKTpob3Zlcnt0ZXh0LWRlY29yYXRpb246IG5vbmU7fWE6d2hlcmUoOm5vdCgud3AtZWxlbWVudC1idXR0b24pKTpmb2N1c3t0ZXh0LWRlY29yYXRpb246IHVuZGVybGluZSBkYXNoZWQ7fWE6d2hlcmUoOm5vdCgud3AtZWxlbWVudC1idXR0b24pKTphY3RpdmV7Y29sb3I6IHZhcigtLXdwLS1wcmVzZXQtLWNvbG9yLS1zZWNvbmRhcnkpO3RleHQtZGVjb3JhdGlvbjogbm9uZTt9aDEsIGgyLCBoMywgaDQsIGg1LCBoNntmb250LXdlaWdodDogNDAwO2xpbmUtaGVpZ2h0OiAxLjQ7fWgxe2ZvbnQtc2l6ZTogY2xhbXAoMi43MTlyZW0sIDIuNzE5cmVtICsgKCgxdncgLSAwLjQ4cmVtKSAqIDEuNzQyKSwgMy42MjVyZW0pO2xpbmUtaGVpZ2h0OiAxLjI7fWgye2ZvbnQtc2l6ZTogY2xhbXAoMi42MjVyZW0sIGNhbGMoMi42MjVyZW0gKyAoKDF2dyAtIDAuNDhyZW0pICogOC40MTM1KSksIDMuMjVyZW0pO2xpbmUtaGVpZ2h0OiAxLjI7fWgze2ZvbnQtc2l6ZTogdmFyKC0td3AtLXByZXNldC0tZm9udC1zaXplLS14LWxhcmdlKTt9aDR7Zm9udC1zaXplOiB2YXIoLS13cC0tcHJlc2V0LS1mb250LXNpemUtLWxhcmdlKTt9aDV7Zm9udC1zaXplOiB2YXIoLS13cC0tcHJlc2V0LS1mb250LXNpemUtLW1lZGl1bSk7Zm9udC13ZWlnaHQ6IDcwMDt0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlO31oNntmb250LXNpemU6IHZhcigtLXdwLS1wcmVzZXQtLWZvbnQtc2l6ZS0tbWVkaXVtKTt0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlO30ud3AtZWxlbWVudC1idXR0b24sIC53cC1ibG9jay1idXR0b25fX2xpbmt7YmFja2dyb3VuZC1jb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLXByaW1hcnkpO2JvcmRlci1yYWRpdXM6IDA7Ym9yZGVyLXdpZHRoOiAwO2NvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tY29udHJhc3QpO2ZvbnQtZmFtaWx5OiBpbmhlcml0O2ZvbnQtc2l6ZTogaW5oZXJpdDtsaW5lLWhlaWdodDogaW5oZXJpdDtwYWRkaW5nOiBjYWxjKDAuNjY3ZW0gKyAycHgpIGNhbGMoMS4zMzNlbSArIDJweCk7dGV4dC1kZWNvcmF0aW9uOiBub25lO30ud3AtZWxlbWVudC1idXR0b246dmlzaXRlZCwgLndwLWJsb2NrLWJ1dHRvbl9fbGluazp2aXNpdGVke2NvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tY29udHJhc3QpO30ud3AtZWxlbWVudC1idXR0b246aG92ZXIsIC53cC1ibG9jay1idXR0b25fX2xpbms6aG92ZXJ7YmFja2dyb3VuZC1jb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWNvbnRyYXN0KTtjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWJhc2UpO30ud3AtZWxlbWVudC1idXR0b246Zm9jdXMsIC53cC1ibG9jay1idXR0b25fX2xpbms6Zm9jdXN7YmFja2dyb3VuZC1jb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWNvbnRyYXN0KTtjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWJhc2UpO30ud3AtZWxlbWVudC1idXR0b246YWN0aXZlLCAud3AtYmxvY2stYnV0dG9uX19saW5rOmFjdGl2ZXtiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tc2Vjb25kYXJ5KTtjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWJhc2UpO30uaGFzLWJsYWNrLWNvbG9ye2NvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tYmxhY2spICFpbXBvcnRhbnQ7fS5oYXMtY3lhbi1ibHVpc2gtZ3JheS1jb2xvcntjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWN5YW4tYmx1aXNoLWdyYXkpICFpbXBvcnRhbnQ7fS5oYXMtd2hpdGUtY29sb3J7Y29sb3I6IHZhcigtLXdwLS1wcmVzZXQtLWNvbG9yLS13aGl0ZSkgIWltcG9ydGFudDt9Lmhhcy1wYWxlLXBpbmstY29sb3J7Y29sb3I6IHZhcigtLXdwLS1wcmVzZXQtLWNvbG9yLS1wYWxlLXBpbmspICFpbXBvcnRhbnQ7fS5oYXMtdml2aWQtcmVkLWNvbG9ye2NvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tdml2aWQtcmVkKSAhaW1wb3J0YW50O30uaGFzLWx1bWlub3VzLXZpdmlkLW9yYW5nZS1jb2xvcntjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWx1bWlub3VzLXZpdmlkLW9yYW5nZSkgIWltcG9ydGFudDt9Lmhhcy1sdW1pbm91cy12aXZpZC1hbWJlci1jb2xvcntjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWx1bWlub3VzLXZpdmlkLWFtYmVyKSAhaW1wb3J0YW50O30uaGFzLWxpZ2h0LWdyZWVuLWN5YW4tY29sb3J7Y29sb3I6IHZhcigtLXdwLS1wcmVzZXQtLWNvbG9yLS1saWdodC1ncmVlbi1jeWFuKSAhaW1wb3J0YW50O30uaGFzLXZpdmlkLWdyZWVuLWN5YW4tY29sb3J7Y29sb3I6IHZhcigtLXdwLS1wcmVzZXQtLWNvbG9yLS12aXZpZC1ncmVlbi1jeWFuKSAhaW1wb3J0YW50O30uaGFzLXBhbGUtY3lhbi1ibHVlLWNvbG9ye2NvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tcGFsZS1jeWFuLWJsdWUpICFpbXBvcnRhbnQ7fS5oYXMtdml2aWQtY3lhbi1ibHVlLWNvbG9ye2NvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tdml2aWQtY3lhbi1ibHVlKSAhaW1wb3J0YW50O30uaGFzLXZpdmlkLXB1cnBsZS1jb2xvcntjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLXZpdmlkLXB1cnBsZSkgIWltcG9ydGFudDt9Lmhhcy1iYXNlLWNvbG9ye2NvbG9yOiB2YXIoLS13cC0tcHJlc2V0LS1jb2xvci0tYmFzZSkgIWltcG9ydGFudDt9Lmhhcy1jb250cmFzdC1jb2xvcntjb2xvcjogdmFyKC0td3AtLXByZXNldC0tY29sb3ItLWNvbnRyYXN0KSAhaW1wb3J0YW50O30uaGFzLXBy