<?xml version="1.0"?>
<!DOCTYPE issues [
<!ELEMENT issues (issue*)>
<!ATTLIST issues burpVersion CDATA "">
<!ATTLIST issues exportTime CDATA "">
<!ELEMENT issue (serialNumber, type, name, host, path, location, severity, confidence, issueBackground?, remediationBackground?, references?, vulnerabilityClassifications?, issueDetail?, issueDetailItems?, remediationDetail?, requestresponse*, collaboratorEvent*, infiltratorEvent*, staticAnalysis*, dynamicAnalysis*, prototypePollution*)>
<!ELEMENT serialNumber (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host ip CDATA "">
<!ELEMENT path (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT confidence (#PCDATA)>
<!ELEMENT issueBackground (#PCDATA)>
<!ELEMENT remediationBackground (#PCDATA)>
<!ELEMENT references (#PCDATA)>
<!ELEMENT vulnerabilityClassifications (#PCDATA)>
<!ELEMENT issueDetail (#PCDATA)>
<!ELEMENT issueDetailItems (issueDetailItem*)>
<!ELEMENT issueDetailItem (#PCDATA)>
<!ELEMENT remediationDetail (#PCDATA)>
<!ELEMENT requestresponse (request?, response?, responseRedirected?)>
<!ELEMENT request (#PCDATA)>
<!ATTLIST request method CDATA "">
<!ATTLIST request base64 (true|false) "false">
<!ELEMENT response (#PCDATA)>
<!ATTLIST response base64 (true|false) "false">
<!ELEMENT responseRedirected (#PCDATA)>
<!ELEMENT sender (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ELEMENT conversation (#PCDATA)>
<!ELEMENT recipient (#PCDATA)>
<!ELEMENT recipients (recipient*)>
<!ELEMENT smtp (sender, recipients, message, conversation)>
<!ELEMENT collaboratorEvent (interactionType, originIp, time, lookupType?, lookupHost?, requestresponse?, smtp?)>
<!ELEMENT interactionType (#PCDATA)>
<!ELEMENT originIp (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT lookupType (#PCDATA)>
<!ELEMENT lookupHost (#PCDATA)>
<!ELEMENT infiltratorEvent (parameterName, platform, signature, stackTrace?, parameterValue?, collaboratorEvent)>
<!ELEMENT parameterName (#PCDATA)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT signature (#PCDATA)>
<!ELEMENT stackTrace (#PCDATA)>
<!ELEMENT parameterValue (#PCDATA)>
<!ELEMENT dynamicAnalysis (source, sink, sourceStackTrace, sinkStackTrace, eventListenerStackTrace, sourceValue, sinkValue, eventHandlerData, eventHandlerDataType, eventHandlerManipulatedData, poc, origin, isOriginChecked, sourceElementId, sourceElementName, eventFiredEventName, eventFiredElementId, eventFiredElementName, eventFiredOuterHtml)>
<!ELEMENT prototypePollution (poc, pollutionTechnique, pollutionType)>
<!ELEMENT staticAnalysis (source, sink, codeSnippets)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT sink (#PCDATA)>
<!ELEMENT sourceStackTrace (#PCDATA)>
<!ELEMENT sinkStackTrace (#PCDATA)>
<!ELEMENT eventListenerStackTrace (#PCDATA)>
<!ELEMENT sourceValue (#PCDATA)>
<!ELEMENT sinkValue (#PCDATA)>
<!ELEMENT eventHandlerData (#PCDATA)>
<!ELEMENT eventHandlerDataType (#PCDATA)>
<!ELEMENT sourceElementId (#PCDATA)>
<!ELEMENT sourceElementName (#PCDATA)>
<!ELEMENT eventFiredEventName (#PCDATA)>
<!ELEMENT eventFiredElementId (#PCDATA)>
<!ELEMENT eventFiredElementName (#PCDATA)>
<!ELEMENT eventFiredOuterHtml (#PCDATA)>
<!ELEMENT eventHandlerManipulatedData (#PCDATA)>
<!ELEMENT poc (#PCDATA)>
<!ELEMENT origin (#PCDATA)>
<!ELEMENT isOriginChecked (#PCDATA)>
<!ELEMENT codeSnippets (codeSnippet*)>
<!ELEMENT codeSnippet (#PCDATA)>
<!ELEMENT pollutionTechnique (#PCDATA)>
<!ELEMENT pollutionType (#PCDATA)>
]>
<issues burpVersion="2023.8.1" exportTime="Sat Aug 12 17:51:46 GMT 2023">
  <issue>
    <serialNumber>6341568177071703040</serialNumber>
    <type>134217728</type>
    <name><![CDATA[Session token in URL]]></name>
    <host ip="172.20.0.3">http://web</host>
    <path><![CDATA[/wp-admin/admin-ajax.php]]></path>
    <location><![CDATA[/wp-admin/admin-ajax.php]]></location>
    <severity>Medium</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[<p>Sensitive information within URLs may be logged in various locations, including the user's browser, the web server, and any forward or reverse proxy servers between the two endpoints. URLs may also be displayed on-screen, bookmarked or emailed around by users. They may be disclosed to third parties via the Referer header when any off-site links are followed. Placing session tokens into the URL increases the risk that they will be captured by an attacker.</p>]]></issueBackground>
    <remediationBackground><![CDATA[<p>Applications should use an alternative mechanism for transmitting session tokens, such as HTTP cookies or hidden fields in forms that are submitted using the POST method.</p>]]></remediationBackground>
    <issueDetail><![CDATA[The URL in the request appears to contain a session token within the query string:<ul><li>http://web/wp-admin/admin-ajax.php?public_key=fuzz&amp;_wpnonce=fuzz&amp;updraft_key_index=fuzz&amp;action=updraftcentral_receivepublickey</li></ul>]]></issueDetail>
    <issueDetailItems>
      <issueDetailItem><![CDATA[http://web/wp-admin/admin-ajax.php?public_key=fuzz&_wpnonce=fuzz&updraft_key_index=fuzz&action=updraftcentral_receivepublickey]]></issueDetailItem>
    </issueDetailItems>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC93cC1hZG1pbi9hZG1pbi1hamF4LnBocD9wdWJsaWNfa2V5PWZ1enomX3dwbm9uY2U9ZnV6eiZ1cGRyYWZ0X2tleV9pbmRleD1mdXp6JmFjdGlvbj11cGRyYWZ0Y2VudHJhbF9yZWNlaXZlcHVibGlja2V5IEhUVFAvMS4wDQpIb3N0OiB3ZWINCg0K]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgNDAwIEJhZCBSZXF1ZXN0DQpEYXRlOiBTYXQsIDEyIEF1ZyAyMDIzIDE3OjQ4OjQ1IEdNVA0KU2VydmVyOiBBcGFjaGUvMi40LjU2IChEZWJpYW4pDQpDb250ZW50LUxlbmd0aDogMzAyDQpDb25uZWN0aW9uOiBjbG9zZQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWw7IGNoYXJzZXQ9aXNvLTg4NTktMQ0KDQo8IURPQ1RZUEUgSFRNTCBQVUJMSUMgIi0vL0lFVEYvL0RURCBIVE1MIDIuMC8vRU4iPgo8aHRtbD48aGVhZD4KPHRpdGxlPjQwMCBCYWQgUmVxdWVzdDwvdGl0bGU+CjwvaGVhZD48Ym9keT4KPGgxPkJhZCBSZXF1ZXN0PC9oMT4KPHA+WW91ciBicm93c2VyIHNlbnQgYSByZXF1ZXN0IHRoYXQgdGhpcyBzZXJ2ZXIgY291bGQgbm90IHVuZGVyc3RhbmQuPGJyIC8+CjwvcD4KPGhyPgo8YWRkcmVzcz5BcGFjaGUvMi40LjU2IChEZWJpYW4pIFNlcnZlciBhdCAxNzIuMjAuMC4zIFBvcnQgODA8L2FkZHJlc3M+CjwvYm9keT48L2h0bWw+Cg==]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>1908229831425585152</serialNumber>
    <type>134217728</type>
    <name><![CDATA[Private IP addresses disclosed]]></name>
    <host ip="172.20.0.3">http://web</host>
    <path><![CDATA[/wp-admin/admin-ajax.php]]></path>
    <location><![CDATA[/wp-admin/admin-ajax.php]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[<p>RFC 1918 specifies ranges of IP addresses that are reserved for use in private networks and cannot be routed on the public Internet. Although various methods exist by which an attacker can determine the public IP addresses in use by an organization, the private addresses used internally cannot usually be determined in the same ways.</p>
<p>Discovering the private addresses used within an organization can help an attacker in carrying out network-layer attacks aiming to penetrate the organization's internal infrastructure. </p>]]></issueBackground>
    <remediationBackground><![CDATA[<p>There is not usually any good reason to disclose the internal IP addresses used within an organization's infrastructure. If these are being returned in service banners or debug messages, then the relevant services should be configured to mask the private addresses. If they are being used to track back-end servers for load balancing purposes, then the addresses should be rewritten with innocuous identifiers from which an attacker cannot infer any useful information about the infrastructure.</p>]]></remediationBackground>
    <issueDetail><![CDATA[The following RFC 1918 IP address was disclosed in the response:<ul><li>172.20.0.3</li></ul>]]></issueDetail>
    <issueDetailItems>
      <issueDetailItem><![CDATA[172.20.0.3]]></issueDetailItem>
    </issueDetailItems>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC93cC1hZG1pbi9hZG1pbi1hamF4LnBocD9wdWJsaWNfa2V5PWZ1enomX3dwbm9uY2U9ZnV6eiZ1cGRyYWZ0X2tleV9pbmRleD1mdXp6JmFjdGlvbj11cGRyYWZ0Y2VudHJhbF9yZWNlaXZlcHVibGlja2V5IEhUVFAvMS4wDQpIb3N0OiB3ZWINCg0K]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgNDAwIEJhZCBSZXF1ZXN0DQpEYXRlOiBTYXQsIDEyIEF1ZyAyMDIzIDE3OjQ4OjQ1IEdNVA0KU2VydmVyOiBBcGFjaGUvMi40LjU2IChEZWJpYW4pDQpDb250ZW50LUxlbmd0aDogMzAyDQpDb25uZWN0aW9uOiBjbG9zZQ0KQ29udGVudC1UeXBlOiB0ZXh0L2h0bWw7IGNoYXJzZXQ9aXNvLTg4NTktMQ0KDQo8IURPQ1RZUEUgSFRNTCBQVUJMSUMgIi0vL0lFVEYvL0RURCBIVE1MIDIuMC8vRU4iPgo8aHRtbD48aGVhZD4KPHRpdGxlPjQwMCBCYWQgUmVxdWVzdDwvdGl0bGU+CjwvaGVhZD48Ym9keT4KPGgxPkJhZCBSZXF1ZXN0PC9oMT4KPHA+WW91ciBicm93c2VyIHNlbnQgYSByZXF1ZXN0IHRoYXQgdGhpcyBzZXJ2ZXIgY291bGQgbm90IHVuZGVyc3RhbmQuPGJyIC8+CjwvcD4KPGhyPgo8YWRkcmVzcz5BcGFjaGUvMi40LjU2IChEZWJpYW4pIFNlcnZlciBhdCAxNzIuMjAuMC4zIFBvcnQgODA8L2FkZHJlc3M+CjwvYm9keT48L2h0bWw+Cg==]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>7861376911389720576</serialNumber>
    <type>134217728</type>
    <name><![CDATA[Input returned in response (reflected)]]></name>
    <host ip="172.20.0.3">http://web</host>
    <path><![CDATA[/wp-admin/admin-ajax.php]]></path>
    <location><![CDATA[/wp-admin/admin-ajax.php]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[<p>Reflection of input arises when data is copied from a request and echoed into the application's immediate response.</p><p>Input being returned in application responses is not a vulnerability in its own right. However, it is a prerequisite for many client-side vulnerabilities, including cross-site scripting, open redirection, content spoofing, and response header injection. Additionally, some server-side vulnerabilities such as SQL injection are often easier to identify and exploit when input is returned in responses. In applications where input retrieval is rare and the environment is resistant to automated testing (for example, due to a web application firewall), it might be worth subjecting instances of it to focused manual testing. </p>]]></issueBackground>
    <issueDetail><![CDATA[The value of the <b>public_key</b> request parameter is copied into the application's response.]]></issueDetail>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC93cC1hZG1pbi9hZG1pbi1hamF4LnBocD9wdWJsaWNfa2V5PWZ1enplNjgzcGF0bzhwJl93cG5vbmNlPWZ1enomdXBkcmFmdF9rZXlfaW5kZXg9ZnV6eiZhY3Rpb249dXBkcmFmdGNlbnRyYWxfcmVjZWl2ZXB1YmxpY2tleSBIVFRQLzEuMA0KSG9zdDogd2ViDQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBTYXQsIDEyIEF1ZyAyMDIzIDE3OjQ5OjA2IEdNVA0KU2VydmVyOiBBcGFjaGUvMi40LjU2IChEZWJpYW4pDQpYLVBvd2VyZWQtQnk6IFBIUC84LjEuMTgNClgtUm9ib3RzLVRhZzogbm9pbmRleA0KWC1Db250ZW50LVR5cGUtT3B0aW9uczogbm9zbmlmZg0KRXhwaXJlczogV2VkLCAxMSBKYW4gMTk4NCAwNTowMDowMCBHTVQNCkNhY2hlLUNvbnRyb2w6IG5vLWNhY2hlLCBtdXN0LXJldmFsaWRhdGUsIG1heC1hZ2U9MA0KUmVmZXJyZXItUG9saWN5OiBzdHJpY3Qtb3JpZ2luLXdoZW4tY3Jvc3Mtb3JpZ2luDQpYLUZyYW1lLU9wdGlvbnM6IFNBTUVPUklHSU4NClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KQ29udGVudC1MZW5ndGg6IDEzNDUNCkNvbm5lY3Rpb246IGNsb3NlDQpDb250ZW50LVR5cGU6IHRleHQvaHRtbDsgY2hhcnNldD1VVEYtOA0KDQoKPGh0bWw+PGhlYWQ+PHRpdGxlPlVwZHJhZnRDZW50cmFsPC90aXRsZT48c3R5bGU+Ym9keSB7dGV4dC1hbGlnbjogY2VudGVyO2ZvbnQtZmFtaWx5OiBIZWx2ZXRpY2EsQXJpYWwsTHVjaWRhLHNhbnMtc2VyaWY7YmFja2dyb3VuZC1jb2xvcjogI0E2NEMxQTtjb2xvcjogI0ZGRjtoZWlnaHQ6IDEwMCU7d2lkdGg6IDEwMCU7bWFyZ2luOiAwO3BhZGRpbmc6IDA7fSNtYWluIHtoZWlnaHQ6IDEwMCU7d2lkdGg6IDEwMCU7ZGlzcGxheTogdGFibGU7fSN3cmFwcGVyIHtkaXNwbGF5OiB0YWJsZS1jZWxsO2hlaWdodDogMTAwJTt2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlO31oMSB7bWFyZ2luLWJvdHRvbTogNXB4O31oMiB7bWFyZ2luLXRvcDogMDtmb250LXNpemU6IDIycHg7Y29sb3I6ICNGRkY7fSNidG4tY2xvc2Uge2NvbG9yOiAjRkZGO2ZvbnQtc2l6ZTogMjBweDtmb250LXdlaWdodDogNTAwO3BhZGRpbmc6IC4zZW0gMWVtO2xpbmUtaGVpZ2h0OiAxLjdlbSAhaW1wb3J0YW50O2JhY2tncm91bmQtY29sb3I6IHRyYW5zcGFyZW50O2JhY2tncm91bmQtc2l6ZTogY292ZXI7YmFja2dyb3VuZC1wb3NpdGlvbjogNTAlO2JhY2tncm91bmQtcmVwZWF0OiBuby1yZXBlYXQ7Ym9yZGVyOiAycHggc29saWQ7Ym9yZGVyLXJhZGl1czogM3B4Oy13ZWJraXQtdHJhbnNpdGlvbi1kdXJhdGlvbjogLjJzO3RyYW5zaXRpb24tZHVyYXRpb246IC4yczstd2Via2l0LXRyYW5zaXRpb24tcHJvcGVydHk6IGFsbCAhaW1wb3J0YW50O3RyYW5zaXRpb24tcHJvcGVydHk6IGFsbCAhaW1wb3J0YW50O3RleHQtZGVjb3JhdGlvbjogbm9uZTt9I2J0bi1jbG9zZTpob3ZlciB7YmFja2dyb3VuZC1jb2xvcjogI0RFNjcyNjt9PC9zdHlsZT48L2hlYWQ+PGJvZHk+PGRpdiBpZD0ibWFpbiI+PGRpdiBpZD0id3JhcHBlciI+PGltZyBzcmM9Imh0dHA6Ly93ZWIvd3AtY29udGVudC9wbHVnaW5zL3VwZHJhZnRwbHVzL2NlbnRyYWwvaW1hZ2VzL3VkLWxvZ28ucG5nIiB3aWR0aD0iNjAiIC8+IDxoMT5VcGRyYWZ0Q2VudHJhbCBDb25uZWN0aW9uPC9oMT48aDI+aHR0cDovL3dlYjwvaDI+PHA+PHN0cm9uZz5BIG5ldyBVcGRyYWZ0Q2VudHJhbCBjb25uZWN0aW9uIGhhcyBub3QgYmVlbiBtYWRlLjwvc3Ryb25nPjxicj5UaGUga2V5IHJlZmVycmVkIHRvIHdhcyB1bmtub3duLjwvcD48cD48YSBpZD0iYnRuLWNsb3NlIiBocmVmPSJodHRwOi8vd2ViL3dwLWFkbWluL2FkbWluLWFqYXgucGhwP3B1YmxpY19rZXk9ZnV6emU2ODNwYXRvOHAmIzAzODtfd3Bub25jZT1mdXp6JiMwMzg7dXBkcmFmdF9rZXlfaW5kZXg9ZnV6eiIgb25jbGljaz0id2luZG93LmNsb3NlKCk7Ij5DbG9zZTwvYT48L3A+PC9kaXY+PC9kaXY+]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>6489961594171006976</serialNumber>
    <type>134217728</type>
    <name><![CDATA[Input returned in response (reflected)]]></name>
    <host ip="172.20.0.3">http://web</host>
    <path><![CDATA[/wp-admin/admin-ajax.php]]></path>
    <location><![CDATA[/wp-admin/admin-ajax.php]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[<p>Reflection of input arises when data is copied from a request and echoed into the application's immediate response.</p><p>Input being returned in application responses is not a vulnerability in its own right. However, it is a prerequisite for many client-side vulnerabilities, including cross-site scripting, open redirection, content spoofing, and response header injection. Additionally, some server-side vulnerabilities such as SQL injection are often easier to identify and exploit when input is returned in responses. In applications where input retrieval is rare and the environment is resistant to automated testing (for example, due to a web application firewall), it might be worth subjecting instances of it to focused manual testing. </p>]]></issueBackground>
    <issueDetail><![CDATA[The value of the <b>_wpnonce</b> request parameter is copied into the application's response.]]></issueDetail>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC93cC1hZG1pbi9hZG1pbi1hamF4LnBocD9wdWJsaWNfa2V5PWZ1enomX3dwbm9uY2U9ZnV6ejJsZTIzaHhoY2gmdXBkcmFmdF9rZXlfaW5kZXg9ZnV6eiZhY3Rpb249dXBkcmFmdGNlbnRyYWxfcmVjZWl2ZXB1YmxpY2tleSBIVFRQLzEuMA0KSG9zdDogd2ViDQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBTYXQsIDEyIEF1ZyAyMDIzIDE3OjUwOjMzIEdNVA0KU2VydmVyOiBBcGFjaGUvMi40LjU2IChEZWJpYW4pDQpYLVBvd2VyZWQtQnk6IFBIUC84LjEuMTgNClgtUm9ib3RzLVRhZzogbm9pbmRleA0KWC1Db250ZW50LVR5cGUtT3B0aW9uczogbm9zbmlmZg0KRXhwaXJlczogV2VkLCAxMSBKYW4gMTk4NCAwNTowMDowMCBHTVQNCkNhY2hlLUNvbnRyb2w6IG5vLWNhY2hlLCBtdXN0LXJldmFsaWRhdGUsIG1heC1hZ2U9MA0KUmVmZXJyZXItUG9saWN5OiBzdHJpY3Qtb3JpZ2luLXdoZW4tY3Jvc3Mtb3JpZ2luDQpYLUZyYW1lLU9wdGlvbnM6IFNBTUVPUklHSU4NClZhcnk6IEFjY2VwdC1FbmNvZGluZw0KQ29udGVudC1MZW5ndGg6IDEzNDUNCkNvbm5lY3Rpb246IGNsb3NlDQpDb250ZW50LVR5cGU6IHRleHQvaHRtbDsgY2hhcnNldD1VVEYtOA0KDQoKPGh0bWw+PGhlYWQ+PHRpdGxlPlVwZHJhZnRDZW50cmFsPC90aXRsZT48c3R5bGU+Ym9keSB7dGV4dC1hbGlnbjogY2VudGVyO2ZvbnQtZmFtaWx5OiBIZWx2ZXRpY2EsQXJpYWwsTHVjaWRhLHNhbnMtc2VyaWY7YmFja2dyb3VuZC1jb2xvcjogI0E2NEMxQTtjb2xvcjogI0ZGRjtoZWlnaHQ6IDEwMCU7d2lkdGg6IDEwMCU7bWFyZ2luOiAwO3BhZGRpbmc6IDA7fSNtYWluIHtoZWlnaHQ6IDEwMCU7d2lkdGg6IDEwMCU7ZGlzcGxheTogdGFibGU7fSN3cmFwcGVyIHtkaXNwbGF5OiB0YWJsZS1jZWxsO2hlaWdodDogMTAwJTt2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlO31oMSB7bWFyZ2luLWJvdHRvbTogNXB4O31oMiB7bWFyZ2luLXRvcDogMDtmb250LXNpemU6IDIycHg7Y29sb3I6ICNGRkY7fSNidG4tY2xvc2Uge2NvbG9yOiAjRkZGO2ZvbnQtc2l6ZTogMjBweDtmb250LXdlaWdodDogNTAwO3BhZGRpbmc6IC4zZW0gMWVtO2xpbmUtaGVpZ2h0OiAxLjdlbSAhaW1wb3J0YW50O2JhY2tncm91bmQtY29sb3I6IHRyYW5zcGFyZW50O2JhY2tncm91bmQtc2l6ZTogY292ZXI7YmFja2dyb3VuZC1wb3NpdGlvbjogNTAlO2JhY2tncm91bmQtcmVwZWF0OiBuby1yZXBlYXQ7Ym9yZGVyOiAycHggc29saWQ7Ym9yZGVyLXJhZGl1czogM3B4Oy13ZWJraXQtdHJhbnNpdGlvbi1kdXJhdGlvbjogLjJzO3RyYW5zaXRpb24tZHVyYXRpb246IC4yczstd2Via2l0LXRyYW5zaXRpb24tcHJvcGVydHk6IGFsbCAhaW1wb3J0YW50O3RyYW5zaXRpb24tcHJvcGVydHk6IGFsbCAhaW1wb3J0YW50O3RleHQtZGVjb3JhdGlvbjogbm9uZTt9I2J0bi1jbG9zZTpob3ZlciB7YmFja2dyb3VuZC1jb2xvcjogI0RFNjcyNjt9PC9zdHlsZT48L2hlYWQ+PGJvZHk+PGRpdiBpZD0ibWFpbiI+PGRpdiBpZD0id3JhcHBlciI+PGltZyBzcmM9Imh0dHA6Ly93ZWIvd3AtY29udGVudC9wbHVnaW5zL3VwZHJhZnRwbHVzL2NlbnRyYWwvaW1hZ2VzL3VkLWxvZ28ucG5nIiB3aWR0aD0iNjAiIC8+IDxoMT5VcGRyYWZ0Q2VudHJhbCBDb25uZWN0aW9uPC9oMT48aDI+aHR0cDovL3dlYjwvaDI+PHA+PHN0cm9uZz5BIG5ldyBVcGRyYWZ0Q2VudHJhbCBjb25uZWN0aW9uIGhhcyBub3QgYmVlbiBtYWRlLjwvc3Ryb25nPjxicj5UaGUga2V5IHJlZmVycmVkIHRvIHdhcyB1bmtub3duLjwvcD48cD48YSBpZD0iYnRuLWNsb3NlIiBocmVmPSJodHRwOi8vd2ViL3dwLWFkbWluL2FkbWluLWFqYXgucGhwP3B1YmxpY19rZXk9ZnV6eiYjMDM4O193cG5vbmNlPWZ1enoybGUyM2h4aGNoJiMwMzg7dXBkcmFmdF9rZXlfaW5kZXg9ZnV6eiIgb25jbGljaz0id2luZG93LmNsb3NlKCk7Ij5DbG9zZTwvYT48L3A+PC9kaXY+PC9kaXY+]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
</issues>
